#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
matlab -nodisplay -r "addpath(genpath('.')); Mean_Plot"

# The previous version of this file was commented-out and follows below:
#
 matlab -nodisplay -r "addpath(genpath('.')); Free_plot_SC1"
# 
# # The previous version of this file was commented-out and follows below:
# #
 matlab -nodisplay -r "addpath(genpath('.')); Dist_plot_SC2"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
 matlab -nodisplay -r "addpath(genpath('.')); ANOVA_Test_SC1"
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
matlab -nodisplay -r "addpath(genpath('.')); ANOVA_Test_SC2"
# # # # 
# # # 
# # 
# 
